### ISSUE TITLE
已经不更新了吗？

### ISSUE THREAD

**Issue by OXERIS** [Jamesits/proxifier-profiles#11]
很不错的项目呀，真是可惜

**Comment by Jamesits** [comment]
好像也没有什么特别值得更新的吧？

**Comment by OXERIS** [comment]
作为想使用用你配置文件的人，我觉得大陆直连的ip是值得更新的。。

**Comment by OXERIS** [comment]
可能你自己觉得没必要- - ，不过作为非专业的使用者，自己去查找ip并调整格式的工作量和学习成本还是非常大，所以我才希望你更新下去

**Comment by Jamesits** [comment]
直连 IP 每天都在变啦，所以比较推荐用 https://github.com/Jamesits/chnroutes/tree/feature/proxifier 来自己生成。（虽然 chnroutes 的上游也是年久失修来着，而且 Python 2 也停止维护了，但是应该还能用。）

这个列表本身呢倒也不是说没必要更新，里面有些软件都已经停止服务了。不过现在继续频繁维护这个配置文件对我来说成本有点高，主要原因是 Apple 近几年没能拿出什么能让我放心地做主力工作设备的 Mac 产品来，我的工作性质接受不了一万多块钱买台电脑然后一年有三个星期在店里修这样的事情，我又没有闲钱买台电脑放家里供着，所以没办法啦。

**Comment by OXERIS** [comment]
多谢多谢，辛苦了，就是想不定期更新下直连的ip段

James Swineson <notifications@github.com> 于 2020年3月30日周一 20:22写道：
