### ISSUE TITLE
Does this profile could be used on Windows?

### ISSUE THREAD

**Issue by moreoronce** [Jamesits/proxifier-profiles#4]
I have a nuc at home which install Windows and this nuc use proxifier too. Does ur profile could be used on Windoes?

**Comment by Jamesits** [comment]
I don't think so. My profile uses a lot of filtering using process names so it won't work well with Windows. Also Proxifier won't work with UWP apps.

**Comment by moreoronce** [comment]
@Jamesits  i've pull ur profile and edited it to make it suitable for Windows. Anyway there still a question about how to get the right Chinese IPs. I can use GeoIP or ip.cn to get the Chinese IPs in time. But the IPs seems all be subnet mask liked. Are there any solution to make them to IP range?

**Comment by Jamesits** [comment]
I have a modified version of chnroutes ( https://github.com/Jamesits/chnroutes/tree/feature/proxifier ) to generate Chinese IP ranges.

**Comment by moreoronce** [comment]
@Jamesits Cool！ Thanks！
