### ISSUE TITLE
tumblr无法打开

### ISSUE THREAD

**Issue by aotter115** [Jamesits/proxifier-profiles#5]
无法打开tumblr.com在外国网站规则里面设置了*.tumblr.com后可以链接，但是Chrome报错：不安全的链接

**Comment by Jamesits** [comment]
项目说明中提到：

> This is not a replacement of system-level proxy settings. Generally speaking, any application which correctly applies system-level proxy (whether PAC or SOCKS5) are not considered to be included in this ruleset.

对于能够正确处理系统应用层代理服务器设置的程序，例如 Chrome，本项目不予考虑。

另外，关于不安全的链接问题，如果你能够重现此问题的话，麻烦贴上该警告页面的截图（请先点击类似“高级”或者“详细信息”等链接以确保包含具体的证书错误）。如果有条件的话，请附上提取的证书或其属性对话框截图。否则我无法提供进一步的帮助。

**Comment by Jamesits** [comment]
鉴于在数日之内没有回复，我将关闭此 issue。如果您继续遇到相关问题，欢迎 reopen。
