### ISSUE TITLE
Netflix好像没有走代理

### ISSUE THREAD

**Issue by tony1016** [Jamesits/proxifier-profiles#8]
如题，直接被打开中国页面

**Comment by Jamesits** [comment]
As stated in README.md:

> This is not a replacement of system-level proxy settings. Generally speaking, any application which correctly applies system-level proxy (whether PAC or SOCKS5) are not considered to be included in this ruleset.

If you are using the browser version of Netflix, please set the proxy via your browser. I'm not aware of any native Netflix apps on macOS; if there are any and you have issues running it under system proxy, I'd be happy to help you test it. In this case, please provide the application name, download URL and a detailed reproduction procedure.

I'm closing #9 too for a similar reason.
